export {
  activateInput,
  activateOutput,
  apiBase,
  connectBluetooth,
  discoverOnAir,
  fetchStatus,
  getActiveInput,
  getActiveOutput,
  getAirplayMode,
  getEq,
  getSampleRate,
  goldenPathSonos,
  listBluetooth,
  listInputs,
  listOutputs,
  pairAirplay,
  pairBluetooth,
  prettyInput,
  probeOnAir,
  setEq,
  setSampleRate,
  setVolume,
  switchTransports,
  verifyPin,
  wsUrl,
} from "@on-air/control-client";
