#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
ENV_FILE="${HOME}/.eas/on-air.env"
mkdir -p "$(dirname "$ENV_FILE")" "${HOME}/.eas/on-air"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

banner "Publish on-air remote to TestFlight (internal team)"

# ── 1. Paid Apple Developer Program ───────────────────────────────────────
stage "Apple Developer Program"
say "TestFlight internal testing needs a paid Apple Developer Program membership."
say "Expo is already logged in as tsonubin; this step is Apple's side."
open_url "https://developer.apple.com/account"
step "Sign in with the Apple ID that owns the on-air Developer Program team."
step "Confirm Membership is Active (Apple Developer Program, \$99/year)."
step "If you are not enrolled, click Enroll and finish payment before continuing."
if ! confirm "Is the Apple Developer Program membership active?"; then
  warn "Stop here, enroll at https://developer.apple.com/programs/ then re-run this wizard."
  exit 1
fi

# ── 2. App Store Connect API key ──────────────────────────────────────────
stage "App Store Connect API key"
say "An Admin Team Key lets EAS create the app record, signing certs, and upload the IPA."
open_url "https://appstoreconnect.apple.com/access/integrations/api"
step "If you see Request Access, agree to the terms and submit, then wait for approval."
step "Stay on Users and Access → Integrations → App Store Connect API → Team Keys (not Individual Keys)."
step "Click Generate API Key (or the + next to Active)."
step "Name: on-air EAS. Access: Admin. Click Generate."
step "Click Download and save the .p8 — Apple will not let you download it again."
step "Copy Key ID from the key's row (10 characters)."
step "Copy Issuer ID from the top of the same page (UUID)."
ask EXPO_ASC_KEY_ID "Paste the Key ID:"
ask EXPO_ASC_ISSUER_ID "Paste the Issuer ID:"
ask EXPO_ASC_API_KEY_PATH "Path to the downloaded .p8 (e.g. ~/Downloads/AuthKey_${EXPO_ASC_KEY_ID}.p8):"
if [[ -z "$EXPO_ASC_KEY_ID" || -z "$EXPO_ASC_ISSUER_ID" ]]; then
  warn "Key ID and Issuer ID are required."
  exit 1
fi
# Expand ~ and copy out of Downloads into a durable local path.
EXPO_ASC_API_KEY_PATH="${EXPO_ASC_API_KEY_PATH/#\~/$HOME}"
if [[ ! -f "$EXPO_ASC_API_KEY_PATH" ]]; then
  warn "No file at $EXPO_ASC_API_KEY_PATH"
  exit 1
fi
STORED_KEY="${HOME}/.eas/on-air/AuthKey_${EXPO_ASC_KEY_ID}.p8"
cp "$EXPO_ASC_API_KEY_PATH" "$STORED_KEY"
chmod 600 "$STORED_KEY"
EXPO_ASC_API_KEY_PATH="$STORED_KEY"
write_env EXPO_ASC_KEY_ID "$EXPO_ASC_KEY_ID"
write_env EXPO_ASC_ISSUER_ID "$EXPO_ASC_ISSUER_ID"
write_env EXPO_ASC_API_KEY_PATH "$EXPO_ASC_API_KEY_PATH"
note "Private key stored at $EXPO_ASC_API_KEY_PATH (not in the git repo)."

# ── 3. Invite internal testers ────────────────────────────────────────────
stage "Invite internal testers"
say "Internal TestFlight testers must already be App Store Connect users."
say "They are not added by email on the TestFlight tab until they accept this invite."
open_url "https://appstoreconnect.apple.com/access/users"
step "Under People, click +."
step "Enter each teammate's first name, last name, and Apple ID email."
step "Role: Developer (enough for internal TestFlight) or App Manager."
step "Leave app access on on-air remote once the app exists, or All Apps for now."
step "Click Invite. They have 3 days to accept the email."
note "You can skip teammates for now and invite them later; you can still install it yourself."
pause "Press Enter after sending invites (or skipping)."

# ── 4. Build + submit ─────────────────────────────────────────────────────
stage "EAS iOS production build + TestFlight submit"
say "This uploads sources to EAS, signs an App Store IPA, and submits it to App Store Connect."
say "First run creates distribution certs and the app.onair.remote app record."
say "Expect 10–20 minutes. Apple login / 2FA may still appear in this terminal."
note "Bundle ID: app.onair.remote · version 0.1.0 (build 1) · profile production"
if ! confirm "Start the EAS iOS production build and auto-submit to TestFlight?"; then
  warn "Build skipped. Re-run this wizard when ready."
  SKIPPED+=("eas build --platform ios --profile production --auto-submit")
else
  export EXPO_ASC_KEY_ID EXPO_ASC_ISSUER_ID EXPO_ASC_API_KEY_PATH
  (
    cd "$MOBILE_DIR"
    npx --yes eas-cli@latest build \
      --platform ios \
      --profile production \
      --auto-submit
  )
fi

# ── 5. Assign the build in TestFlight ─────────────────────────────────────
stage "Assign the processed build to Internal Testing"
say "Apple emails you when processing finishes (usually 5–15 minutes after submit)."
open_url "https://appstoreconnect.apple.com/apps"
step "Open the on-air remote app (EAS creates it on first submit if it did not exist)."
step "Go to the TestFlight tab."
step "If Internal Testing has no group, click + next to Internal Testing, name it Internal, enable automatic distribution."
step "Open the group → Testers → + and add the teammates who accepted the Users and Access invite."
step "Testers install Apple's TestFlight app, tap the invite email, then Install."
note "Internal builds skip Beta App Review. Builds expire 90 days after upload."
pause "Press Enter after the group exists (the build can still be Processing)."

# ──────────────────────────────────────────────────────────────────────────

finish
note "Re-run later for a new build: the API key is remembered in $ENV_FILE."
note "Testers who have not accepted the App Store Connect invite cannot be added to Internal Testing."
